import PDFDocument from 'pdfkit';

interface IShippingLabelPdfData {
  shipmentId: string;
  trackingNumber: string;
  recipientName: string;
  recipientPhone: string;
  deliveryAddress: string;
  originZone: string;
  destinationZone: string;
  packageDescription: string;
  weight: number;
  codAmount: number;
}

const generateShippingLabelPdf = async (data: IShippingLabelPdfData): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'A6',
      margin: 25,
    });

    const chunks: Buffer[] = [];

    doc.on('data', (chunk: Buffer) => {
      chunks.push(chunk);
    });

    doc.on('end', () => {
      resolve(Buffer.concat(chunks));
    });

    doc.on('error', reject);

    try {
      doc.fontSize(20).font('Helvetica-Bold').text('ParcelRelay', {
        align: 'center',
      });

      doc.moveDown(0.5);

      doc.fontSize(14).font('Helvetica-Bold').text('SHIPPING LABEL', {
        align: 'center',
      });

      doc.moveDown();

      doc.fontSize(11).font('Helvetica-Bold').text('Tracking Number');

      doc.fontSize(16).font('Helvetica-Bold').text(data.trackingNumber, {
        align: 'center',
      });

      doc.moveDown();

      doc.fontSize(10).font('Helvetica').text(`Shipment ID: ${data.shipmentId}`);

      doc.moveDown();

      doc.fontSize(11).font('Helvetica-Bold').text('RECIPIENT');

      doc
        .fontSize(10)
        .font('Helvetica')
        .text(`Name: ${data.recipientName}`)
        .text(`Phone: ${data.recipientPhone}`)
        .text(`Address: ${data.deliveryAddress}`);

      doc.moveDown();

      doc.fontSize(11).font('Helvetica-Bold').text('SHIPMENT');

      doc
        .fontSize(10)
        .font('Helvetica')
        .text(`From: ${data.originZone}`)
        .text(`To: ${data.destinationZone}`)
        .text(`Package: ${data.packageDescription}`)
        .text(`Weight: ${data.weight} kg`)
        .text(`COD: BDT ${data.codAmount.toFixed(2)}`);

      doc.moveDown();

      doc.fontSize(9).font('Helvetica').text('Handle with care. Generated by ParcelRelay.', {
        align: 'center',
      });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

export const shippingLabelPdfUtils = {
  generateShippingLabelPdf,
};
